import { Menu } from '@/componentes/Menu';
import type { NextPage } from 'next';
import { useState, useEffect } from 'react';
import Livro from '@/classes/modelo/Livro';
import Head from 'next/head';
import { LinhaLivro } from '@/componentes/LinhaLivro';

const baseURL = 'http://localhost:3000/api/livros';

const obterLivros = async () => {
  const response = await fetch(baseURL);
  return await response.json();
};

const excluirLivro = async (codigo: number): Promise<boolean> => {
  const response = await fetch(`${baseURL}/${codigo}`, {
    method: 'DELETE',
  });
  const { ok } = await response.json();
  return ok;
};

const LivroLista: NextPage = () => {
  const [livros, setLivros] = useState<Array<Livro>>([]);
  const [carregado, setCarregado] = useState<boolean>(false);

  useEffect(() => {
    obterLivros().then((data: any) => {
      setLivros(data);
      setCarregado(true);
    });
  }, [carregado]);

  const excluir = async (codigo: number) => {
    await excluirLivro(codigo);
    setCarregado(false);
  };
  return (
    <> 
    <style>
        {`table{
          border-radius: 5px;
          overflow:hidden
        }
        `}
      </style>
      <Menu />
        <Head>
          <title>Loja Next</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <main className="container bg-black text-light">
          <h1 className='my-3 display-2 text-center'>Catálogo de Livros</h1>
          <table className="table table-hover">
            <thead>
              <tr className=" table-dark">
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
              </tr>
            </thead>
            <tbody>
              {livros.map((livro) => (
                <LinhaLivro
                  key={livro.codigo}
                  livro={livro}
                  excluir={excluir}
                />
              ))}
            </tbody>
          </table>
        </main>
    </>
  );
};

export default LivroLista;
